/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author linhm
 */
public class FormChooseExcel extends javax.swing.JFrame {

    /**
     * Creates new form FormChoseExcel
     */
    
    private JTable TableTatca;
    private JTable TableChuathanhtoan;
    private JTable TableDathanhtoan;
    private JTable TableSaima;
    
    public FormChooseExcel() {
        initComponents();
    }
    
    public FormChooseExcel(JTable TableTatca,JTable TableChuathanhtoan,JTable TableDathanhtoan,JTable TableSaima) 
    {
        this.TableTatca=TableTatca;
        this.TableChuathanhtoan=TableChuathanhtoan;
        this.TableDathanhtoan=TableDathanhtoan;
        this.TableSaima=TableSaima;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RdTatca = new javax.swing.JRadioButton();
        RdChuathanhtoan = new javax.swing.JRadioButton();
        RdDathanhtoan = new javax.swing.JRadioButton();
        RdSaimahoadon = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Chọn bảng cần xuất Excel");

        RdTatca.setText("Tất  cả");
        RdTatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdTatcaActionPerformed(evt);
            }
        });

        RdChuathanhtoan.setText("Chưa thanh toán");
        RdChuathanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdChuathanhtoanActionPerformed(evt);
            }
        });

        RdDathanhtoan.setText("Đã thanh toán");

        RdSaimahoadon.setText("Sai mã hóa đơn");

        jButton1.setText("Xuất Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdChuathanhtoan)
                    .addComponent(RdDathanhtoan)
                    .addComponent(RdTatca)
                    .addComponent(RdSaimahoadon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(RdTatca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdChuathanhtoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdDathanhtoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RdSaimahoadon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdTatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdTatcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdTatcaActionPerformed

    private void RdChuathanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdChuathanhtoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdChuathanhtoanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try 
        {
                if(RdTatca.isSelected())
                {
                    exportExcel(this.TableTatca);
                }
                if(RdChuathanhtoan.isSelected())
                {
                    exportExcel(this.TableChuathanhtoan);
                }
                if(RdDathanhtoan.isSelected())
                {
                    exportExcel(this.TableDathanhtoan);
                }
                if(RdSaimahoadon.isSelected())
                {
                    exportExcel(this.TableSaima);
                }
        } catch (IOException ex) {
                Logger.getLogger(FormChooseExcel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public  void exportExcel(JTable jTable1) throws FileNotFoundException, IOException
    {
                File file = null;
                JFileChooser chooser = new JFileChooser();
                int choose = chooser.showSaveDialog(chooser);
                if (choose == JFileChooser.APPROVE_OPTION) 
                {
                    file = chooser.getSelectedFile(); 
                }
                HSSFWorkbook fWorkbook = new HSSFWorkbook();
                HSSFSheet fSheet = fWorkbook.createSheet("new Sheet");
                HSSFFont sheetTitleFont = fWorkbook.createFont();
                HSSFCellStyle cellStyle = fWorkbook.createCellStyle();
                TableModel model = jTable1.getModel();
                TableColumnModel tcm = jTable1.getColumnModel();
                HSSFRow hRow = fSheet.createRow((short) 0);
                for(int j = 0; j < tcm.getColumnCount(); j++) 
                {                       
                    HSSFCell cell = hRow.createCell((short) j);
                    cell.setCellValue(tcm.getColumn(j).getHeaderValue().toString());
                    cell.setCellStyle(cellStyle);
                }
                for (int i = 0; i < model.getRowCount(); i++) 
                {
                    HSSFRow fRow = fSheet.createRow((short) i+1);
                    for (int j = 0; j < model.getColumnCount(); j++)
                    {
                        HSSFCell cell = fRow.createCell((short) j);
                        cell.setCellValue(model.getValueAt(i, j).toString());
                        cell.setCellStyle(cellStyle);
                    }
                }
            FileOutputStream fileOutputStream;
            fileOutputStream = new FileOutputStream(file.getPath().toString()+".xls");
            try (BufferedOutputStream bos = new BufferedOutputStream(fileOutputStream)) 
            {
                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
                fWorkbook.write(bos);
            }
            fileOutputStream.close();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChooseExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChooseExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChooseExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChooseExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FormChooseExcel form;
                form = new FormChooseExcel();
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdChuathanhtoan;
    private javax.swing.JRadioButton RdDathanhtoan;
    private javax.swing.JRadioButton RdSaimahoadon;
    private javax.swing.JRadioButton RdTatca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
